/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    'activity-logs': ActivityLog;
    'career-applications': CareerApplication;
    'resume-files': ResumeFile;
    media: Media;
    'product-categories': ProductCategory;
    'product-subcategories': ProductSubcategory;
    products: Product;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    'activity-logs': ActivityLogsSelect<false> | ActivityLogsSelect<true>;
    'career-applications': CareerApplicationsSelect<false> | CareerApplicationsSelect<true>;
    'resume-files': ResumeFilesSelect<false> | ResumeFilesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'product-categories': ProductCategoriesSelect<false> | ProductCategoriesSelect<true>;
    'product-subcategories': ProductSubcategoriesSelect<false> | ProductSubcategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('fa' | 'en') | ('fa' | 'en')[];
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'fa' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * این کاربران فقط برای ورود به پنل مدیریت هستند و حساب مشتری یا بازدیدکننده سایت محسوب نمی‌شوند.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'super-admin' | 'publisher' | 'editor' | 'media-manager';
  /**
   * هر دسترسی مستقل است. فقط کاربری که «مدیریت کاربران» دارد می‌تواند این چک‌لیست را تغییر دهد.
   */
  permissions?: {
    manageAdmins?: boolean | null;
    manageProducts?: boolean | null;
    manageSiteContent?: boolean | null;
    manageSiteSettings?: boolean | null;
    manageMedia?: boolean | null;
    manageCareerApplications?: boolean | null;
    publishContent?: boolean | null;
    viewActivityLog?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * برای امنیت، فقط نام فیلدهای تغییرکرده ثبت می‌شود و مقدار فیلدها، رمزها و secretها ذخیره نمی‌شوند.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity-logs".
 */
export interface ActivityLog {
  id: number;
  actor?: (number | null) | User;
  actorEmail: string;
  action: 'create' | 'update' | 'delete' | 'update-global';
  entityLabel: string;
  entitySlug: string;
  documentID?: string | null;
  documentTitle: string;
  changedFields?:
    | {
        field: string;
        id?: string | null;
      }[]
    | null;
  locale?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * رزومه‌ها اطلاعات شخصی و محرمانه‌اند؛ فقط افراد مسئول منابع انسانی باید به این بخش دسترسی داشته باشند.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "career-applications".
 */
export interface CareerApplication {
  id: number;
  fullName: string;
  phone: string;
  /**
   * فایل‌ها خصوصی‌اند و حذف این درخواست، فایل‌های مرتبط را نیز حذف می‌کند.
   */
  attachments: (number | ResumeFile)[];
  status: 'new' | 'reviewing' | 'contacted' | 'closed';
  locale: 'fa' | 'en';
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * این فایل‌ها خصوصی‌اند و فقط از درخواست همکاری مرتبط مدیریت می‌شوند.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume-files".
 */
export interface ResumeFile {
  id: number;
  originalName: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * تصاویر، ویدئوها و PDFهایی که از پنل آپلود می‌کنید اینجا نگهداری می‌شوند. فایل‌های قدیمیِ داخل پروژه تا زمانی که جایگزین نشوند در این فهرست دیده نمی‌شوند.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories".
 */
export interface ProductCategory {
  id: number;
  title: string;
  /**
   * فقط حروف انگلیسی کوچک، عدد و خط تیره؛ بعداً تغییر ندهید.
   */
  slug: string;
  color: string;
  sortOrder: number;
  /**
   * خالی بگذارید تا همه کارت‌ها دو ستونه باشند.
   */
  fullWidthEvery?: number | null;
  /**
   * برای جایگزینی فایل فعلی، یک رسانه از کتابخانه انتخاب یا فایل جدید بارگذاری کنید.
   */
  backgroundMedia?: (number | null) | Media;
  /**
   * مسیر فایل اولیه فقط برای سازگاری نگه داشته شده است؛ جایگزینی را از فیلد مدیریت رسانه انجام دهید.
   */
  legacyBackgroundPath?: string | null;
  heroItems?:
    | {
        /**
         * برای جایگزینی فایل فعلی، یک رسانه از کتابخانه انتخاب یا فایل جدید بارگذاری کنید.
         */
        media?: (number | null) | Media;
        /**
         * مسیر فایل اولیه فقط برای سازگاری نگه داشته شده است؛ جایگزینی را از فیلد مدیریت رسانه انجام دهید.
         */
        legacySrc?: string | null;
        subcategoryKey?: string | null;
        desktop: {
          left: number;
          width: number;
          bleed: number;
          rotate: number;
          z: number;
        };
        mobile: {
          left: number;
          width: number;
          bleed: number;
          rotate: number;
          z: number;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-subcategories".
 */
export interface ProductSubcategory {
  id: number;
  label: string;
  sectionTitle: string;
  key: string;
  category: number | ProductCategory;
  color: string;
  sortOrder: number;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  subtitle?: string | null;
  ingredients?: string | null;
  feature?: string | null;
  /**
   * شناسه فنی محصول؛ پس از انتشار تغییر ندهید.
   */
  stableKey: string;
  category: number | ProductCategory;
  subcategory: number | ProductSubcategory;
  /**
   * برای جایگزینی فایل فعلی، یک رسانه از کتابخانه انتخاب یا فایل جدید بارگذاری کنید.
   */
  image?: (number | null) | Media;
  /**
   * مسیر فایل اولیه فقط برای سازگاری نگه داشته شده است؛ جایگزینی را از فیلد مدیریت رسانه انجام دهید.
   */
  legacyImagePath?: string | null;
  /**
   * برای جایگزینی فایل فعلی، یک رسانه از کتابخانه انتخاب یا فایل جدید بارگذاری کنید.
   */
  hoverVideo?: (number | null) | Media;
  /**
   * مسیر فایل اولیه فقط برای سازگاری نگه داشته شده است؛ جایگزینی را از فیلد مدیریت رسانه انجام دهید.
   */
  legacyHoverVideoPath?: string | null;
  /**
   * کوچک ۹۵٪، معمولی ۱۰۰٪ و بزرگ ۱۰۵٪ ارتفاع استاندارد کارت است.
   */
  mediaDisplaySize: 'small' | 'normal' | 'large';
  /**
   * برای محصول تازه می‌تواند تا زمان دریافت مشخصات خالی بماند.
   */
  variants?:
    | {
        weight?: string | null;
        dimensions?: string | null;
        barcode?: string | null;
        id?: string | null;
      }[]
    | null;
  sortOrder: number;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * صفحه‌ها از قبل ساخته شده‌اند و قابل افزودن یا حذف نیستند.
   */
  slug: 'home' | 'about' | 'innovation' | 'production' | 'distribution' | 'contact' | 'careers';
  title: string;
  eyebrow: string;
  lead: string;
  /**
   * برای جایگزینی فایل فعلی، یک رسانه از کتابخانه انتخاب یا فایل جدید بارگذاری کنید.
   */
  heroImage?: (number | null) | Media;
  /**
   * مسیر فایل اولیه فقط برای سازگاری نگه داشته شده است؛ جایگزینی را از فیلد مدیریت رسانه انجام دهید.
   */
  legacyHeroImage?: string | null;
  imageAlt: string;
  mark?: string | null;
  accent?: string | null;
  /**
   * هر ردیف دقیقاً یک سکشن سایت است. برای حذف امن، نمایش سکشن را خاموش کنید؛ ساختار سکشن‌ها قابل افزودن یا حذف نیست.
   */
  sections?:
    | {
        sectionKey: string;
        locked?: boolean | null;
        adminLabel: string;
        /**
         * با خاموش‌کردن این گزینه، سکشن و فضای آن کاملاً از صفحه حذف می‌شود؛ اطلاعاتش در CMS باقی می‌ماند.
         */
        enabled?: boolean | null;
        /**
         * این موارد متعلق به طراحی سکشن هستند؛ متنشان قابل ویرایش است اما ساختارشان حذف یا اضافه نمی‌شود.
         */
        copyBlocks?:
          | {
              sourceKey: string;
              adminLabel: string;
              text: string;
              id?: string | null;
            }[]
          | null;
        /**
         * تصویر فعلی را می‌بینید و می‌توانید فایل جایگزین انتخاب کنید.
         */
        imageOverrides?:
          | {
              adminLabel: string;
              replacement?: (number | null) | Media;
              sourcePath: string;
              id?: string | null;
            }[]
          | null;
        /**
         * شماره تلفن، ایمیل، کد پستی و داده‌های ثابت این سکشن.
         */
        valueOverrides?:
          | {
              sourceKey: string;
              adminLabel: string;
              value: string;
              id?: string | null;
            }[]
          | null;
        /**
         * خود نوع لیست بخشی از طراحی است؛ آیتم‌های داخل آن را می‌توانید اضافه، حذف و مرتب کنید.
         */
        lists?:
          | {
              listKey: string;
              adminLabel: string;
              /**
               * افزودن، حذف و جابه‌جایی در این قسمت مجاز است. فقط فیلدهایی نمایش داده می‌شوند که همین بخش از سایت واقعاً مصرف می‌کند.
               */
              items?:
                | {
                    itemKey?: string | null;
                    adminLabel?: string | null;
                    enabled?: boolean | null;
                    title: string;
                    eyebrow?: string | null;
                    subtitle?: string | null;
                    text?: string | null;
                    value?: string | null;
                    secondaryValue?: string | null;
                    details?:
                      | {
                          value: string;
                          id?: string | null;
                        }[]
                      | null;
                    latitude?: number | null;
                    longitude?: number | null;
                    color?: string | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  seo: {
    metaTitle: string;
    metaDescription: string;
  };
  /**
   * این موارد متعلق به طراحی سکشن هستند؛ متنشان قابل ویرایش است اما ساختارشان حذف یا اضافه نمی‌شود.
   */
  copyBlocks?:
    | {
        sourceKey: string;
        adminLabel: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * تصویر فعلی را می‌بینید و می‌توانید فایل جایگزین انتخاب کنید.
   */
  imageOverrides?:
    | {
        adminLabel: string;
        replacement?: (number | null) | Media;
        sourcePath: string;
        id?: string | null;
      }[]
    | null;
  /**
   * شماره تلفن، ایمیل، کد پستی و داده‌های ثابت این سکشن.
   */
  valueOverrides?:
    | {
        sourceKey: string;
        adminLabel: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'activity-logs';
        value: number | ActivityLog;
      } | null)
    | ({
        relationTo: 'career-applications';
        value: number | CareerApplication;
      } | null)
    | ({
        relationTo: 'resume-files';
        value: number | ResumeFile;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'product-categories';
        value: number | ProductCategory;
      } | null)
    | ({
        relationTo: 'product-subcategories';
        value: number | ProductSubcategory;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  permissions?:
    | T
    | {
        manageAdmins?: T;
        manageProducts?: T;
        manageSiteContent?: T;
        manageSiteSettings?: T;
        manageMedia?: T;
        manageCareerApplications?: T;
        publishContent?: T;
        viewActivityLog?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity-logs_select".
 */
export interface ActivityLogsSelect<T extends boolean = true> {
  actor?: T;
  actorEmail?: T;
  action?: T;
  entityLabel?: T;
  entitySlug?: T;
  documentID?: T;
  documentTitle?: T;
  changedFields?:
    | T
    | {
        field?: T;
        id?: T;
      };
  locale?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "career-applications_select".
 */
export interface CareerApplicationsSelect<T extends boolean = true> {
  fullName?: T;
  phone?: T;
  attachments?: T;
  status?: T;
  locale?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume-files_select".
 */
export interface ResumeFilesSelect<T extends boolean = true> {
  originalName?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories_select".
 */
export interface ProductCategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  color?: T;
  sortOrder?: T;
  fullWidthEvery?: T;
  backgroundMedia?: T;
  legacyBackgroundPath?: T;
  heroItems?:
    | T
    | {
        media?: T;
        legacySrc?: T;
        subcategoryKey?: T;
        desktop?:
          | T
          | {
              left?: T;
              width?: T;
              bleed?: T;
              rotate?: T;
              z?: T;
            };
        mobile?:
          | T
          | {
              left?: T;
              width?: T;
              bleed?: T;
              rotate?: T;
              z?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-subcategories_select".
 */
export interface ProductSubcategoriesSelect<T extends boolean = true> {
  label?: T;
  sectionTitle?: T;
  key?: T;
  category?: T;
  color?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  subtitle?: T;
  ingredients?: T;
  feature?: T;
  stableKey?: T;
  category?: T;
  subcategory?: T;
  image?: T;
  legacyImagePath?: T;
  hoverVideo?: T;
  legacyHoverVideoPath?: T;
  mediaDisplaySize?: T;
  variants?:
    | T
    | {
        weight?: T;
        dimensions?: T;
        barcode?: T;
        id?: T;
      };
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  eyebrow?: T;
  lead?: T;
  heroImage?: T;
  legacyHeroImage?: T;
  imageAlt?: T;
  mark?: T;
  accent?: T;
  sections?:
    | T
    | {
        sectionKey?: T;
        locked?: T;
        adminLabel?: T;
        enabled?: T;
        copyBlocks?:
          | T
          | {
              sourceKey?: T;
              adminLabel?: T;
              text?: T;
              id?: T;
            };
        imageOverrides?:
          | T
          | {
              adminLabel?: T;
              replacement?: T;
              sourcePath?: T;
              id?: T;
            };
        valueOverrides?:
          | T
          | {
              sourceKey?: T;
              adminLabel?: T;
              value?: T;
              id?: T;
            };
        lists?:
          | T
          | {
              listKey?: T;
              adminLabel?: T;
              items?:
                | T
                | {
                    itemKey?: T;
                    adminLabel?: T;
                    enabled?: T;
                    title?: T;
                    eyebrow?: T;
                    subtitle?: T;
                    text?: T;
                    value?: T;
                    secondaryValue?: T;
                    details?:
                      | T
                      | {
                          value?: T;
                          id?: T;
                        };
                    latitude?: T;
                    longitude?: T;
                    color?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  copyBlocks?:
    | T
    | {
        sourceKey?: T;
        adminLabel?: T;
        text?: T;
        id?: T;
      };
  imageOverrides?:
    | T
    | {
        adminLabel?: T;
        replacement?: T;
        sourcePath?: T;
        id?: T;
      };
  valueOverrides?:
    | T
    | {
        sourceKey?: T;
        adminLabel?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  brand: {
    name: string;
    tagline: string;
    /**
     * برای جایگزینی فایل فعلی، یک رسانه از کتابخانه انتخاب یا فایل جدید بارگذاری کنید.
     */
    logo?: (number | null) | Media;
    /**
     * مسیر فایل اولیه فقط برای سازگاری نگه داشته شده است؛ جایگزینی را از فیلد مدیریت رسانه انجام دهید.
     */
    legacyLogoPath?: string | null;
  };
  homeHero: {
    eyebrow: string;
    title: string;
    script: string;
    link: string;
    uiAt?: number | null;
    /**
     * برای جایگزینی فایل فعلی، یک رسانه از کتابخانه انتخاب یا فایل جدید بارگذاری کنید.
     */
    poster?: (number | null) | Media;
    /**
     * مسیر فایل اولیه فقط برای سازگاری نگه داشته شده است؛ جایگزینی را از فیلد مدیریت رسانه انجام دهید.
     */
    legacyPosterPath?: string | null;
    /**
     * برای جایگزینی فایل فعلی، یک رسانه از کتابخانه انتخاب یا فایل جدید بارگذاری کنید.
     */
    video?: (number | null) | Media;
    /**
     * مسیر فایل اولیه فقط برای سازگاری نگه داشته شده است؛ جایگزینی را از فیلد مدیریت رسانه انجام دهید.
     */
    legacyVideoPath?: string | null;
  };
  homeAbout: {
    title: string;
    body: string;
    cta: string;
    link: string;
    /**
     * برای جایگزینی فایل فعلی، یک رسانه از کتابخانه انتخاب یا فایل جدید بارگذاری کنید.
     */
    image?: (number | null) | Media;
    /**
     * مسیر فایل اولیه فقط برای سازگاری نگه داشته شده است؛ جایگزینی را از فیلد مدیریت رسانه انجام دهید.
     */
    legacyImagePath?: string | null;
    /**
     * برای جایگزینی فایل فعلی، یک رسانه از کتابخانه انتخاب یا فایل جدید بارگذاری کنید.
     */
    mobileImage?: (number | null) | Media;
    /**
     * مسیر فایل اولیه فقط برای سازگاری نگه داشته شده است؛ جایگزینی را از فیلد مدیریت رسانه انجام دهید.
     */
    legacyMobileImagePath?: string | null;
  };
  footer: {
    heading: string;
    copyright: string;
    contacts?:
      | {
          type: 'phone' | 'fax' | 'email';
          label: string;
          value: string;
          id?: string | null;
        }[]
      | null;
  };
  socials?:
    | {
        provider: 'instagram' | 'linkedin' | 'aparat' | 'youtube' | 'x';
        href: string;
        id?: string | null;
      }[]
    | null;
  catalog: {
    /**
     * برای جایگزینی فایل فعلی، یک رسانه از کتابخانه انتخاب یا فایل جدید بارگذاری کنید.
     */
    file?: (number | null) | Media;
    /**
     * مسیر فایل اولیه فقط برای سازگاری نگه داشته شده است؛ جایگزینی را از فیلد مدیریت رسانه انجام دهید.
     */
    legacyFilePath?: string | null;
    label: string;
  };
  seo: {
    title: string;
    description: string;
  };
  /**
   * برچسب‌های منو، محصولات و پیام‌های مشترک سایت. فارسی و انگلیسی را از انتخابگر زبان ویرایش کنید.
   */
  interfaceCopy?:
    | {
        sourceKey: string;
        adminLabel: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * گزارش‌ها فقط نام فیلدهای تغییرکرده را نگه می‌دارند؛ نه مقدارها، رمز عبور یا secretها.
   */
  audit: {
    retentionDays: number;
  };
  /**
   * نوع و سقف فایل‌ها از اینجا مدیریت می‌شود. سقف سخت امنیتی هر فایل ۱۰ و مجموع فایل‌ها ۲۰ مگابایت است.
   */
  careers: {
    enabled?: boolean | null;
    maxFiles: number;
    maxFileSizeMB: number;
    maxTotalSizeMB: number;
    allowedFileTypes: ('pdf' | 'doc' | 'docx')[];
    /**
     * job پاک‌سازی، درخواست‌ها و فایل‌های قدیمی‌تر از این مدت را با هم حذف می‌کند.
     */
    retentionDays: number;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  brand?:
    | T
    | {
        name?: T;
        tagline?: T;
        logo?: T;
        legacyLogoPath?: T;
      };
  homeHero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        script?: T;
        link?: T;
        uiAt?: T;
        poster?: T;
        legacyPosterPath?: T;
        video?: T;
        legacyVideoPath?: T;
      };
  homeAbout?:
    | T
    | {
        title?: T;
        body?: T;
        cta?: T;
        link?: T;
        image?: T;
        legacyImagePath?: T;
        mobileImage?: T;
        legacyMobileImagePath?: T;
      };
  footer?:
    | T
    | {
        heading?: T;
        copyright?: T;
        contacts?:
          | T
          | {
              type?: T;
              label?: T;
              value?: T;
              id?: T;
            };
      };
  socials?:
    | T
    | {
        provider?: T;
        href?: T;
        id?: T;
      };
  catalog?:
    | T
    | {
        file?: T;
        legacyFilePath?: T;
        label?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  interfaceCopy?:
    | T
    | {
        sourceKey?: T;
        adminLabel?: T;
        text?: T;
        id?: T;
      };
  audit?:
    | T
    | {
        retentionDays?: T;
      };
  careers?:
    | T
    | {
        enabled?: T;
        maxFiles?: T;
        maxFileSizeMB?: T;
        maxTotalSizeMB?: T;
        allowedFileTypes?: T;
        retentionDays?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}